title: ThinkGo
subtitle: "A fast, simple & powerful web framework written in Go (Golang)."
description: "ThinkGo is a fast, simple & powerful web framework written in Go (Golang)."
author: TechLee
language: en
timezone: UTC

url: https://thinkoner.github.io/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:thinkoner/thinkoner.github.io.git

highlight:
  enable: true
  line_number: false

github: thinkoner/thinkgo
