<!-- GitHub star -->
<a class="github-button" href="https://github.com/thinkoner/thinkgo" data-icon="octicon-star" data-show-count="true" aria-label="Star thinkoner/thinkgo on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/thinkoner/thinkgo/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork thinkoner/thinkgo on GitHub">Fork</a>
<script async defer src="https://buttons.github.io/buttons.js"></script>